### ISSUE TITLE
Travis Deployment broken

### ISSUE THREAD

**Issue by Gioyik** [IbagueJS/ibaguejs.github.io#11]
@paleox your latest PR is broken, please check the log: https://api.travis-ci.org/v3/job/526116724/log.txt

cc/ the PR reviewer: @Diegoavilap

**Comment by dresrok** [comment]
This error is so weird, because I added a new image and changed a text, I didn't install any dependency. It could be a conflict between yarn.lock and package-lock.json.

**Comment by dresrok** [comment]
Resolve with #13
